models_dir_path: "/tahoe/data/ckpts/MFM-v2/test_rel/"
input_path: "/tahoe/data/msigdb/cellxgene_data/rep_1.h5ad.gz"
output_dir: "./gene_embs"
ensembl_to_gene_path: "/tahoe/gits/shreshth_sandbox/msigdb_notebooks/vevo_v2_ensembl_to_gene_name.json"
gene_col: feature_name
n_hvg: null
embeddings_path: "./gene_embs"
signatures_path: "/tahoe/data/msigdb/hallmarks"
filter: False
min_sig_size: 25
max_sig_size: None
min_hits_per_gene: 10
chunk_size: 30000
batch_size: 32
max_length: 8192
benchmark:
  seeds: [0]
  mods: [GE, TE, EA]
  gene_set_paths: []
  output_dir: path/to/benchmark_output
visualization:
  pred_dir: path/to/benchmark_output
  output: path/to/plot.png
