model_name: "tx1"
paths:
  # if you have a local checkpoint, use model_dir instead of hf_*
  hf_repo_id: "tahoebio/Tahoe-x1"
  hf_model_size: "70m"
  adata_input: "/tahoe/data/datasets/benchmark/kim2020_lung/kim_test.h5ad"
  adata_output: "./pred_adata.h5ad"
data:
  gene_id_key: "ensembl_id"
predict:
  batch_size: 64
  seq_len_dataset: 2048
  num_workers: 8
  prefetch_factor: 48
  return_gene_embeddings: False
