paths:
  model_dir: "/tahoe/data/ckpts/MFM-v2/release/mosaicfm-70m-VQ9aRB"
  adata_input: "/tahoe/data/datasets/benchmark/kim2020_lung/kim_train.h5ad" #"/tahoe/data/datasets/benchmark/CCLE/ccle.h5ad" # "/tahoe/data/datasets/benchmark/tahoe/Tahoe50k_train.h5ad"
  cell_output: "./kim_cell_embeddings.h5ad" #"/tahoe/data/datasets/benchmark/CCLE/cell_embeddings.h5ad"
  gene_output: "./kim_gene_embeddings.npz"
  drug_to_id_path: "drug_to_id_pad.json"
  drug_fps_path: "drug_fps_pad.npy"
data:
  cell_type_key: "cell_type" #"OncotreeLineage"
  gene_id_key: "ensembl_id" #"feature_id"
predict:
  batch_size: 64
  seq_len_dataset: 2048 #8192
  num_workers: 8
  return_genes: True  # Whether to extract gene embeddings
